### PR TITLE
Minor updates to PyTorch Pipelines notebook

### PR DESCRIPTION
**Pull request by sararob**
Made a few minor updates to this notebook:
* Replaced AI Platform with Vertex AI
* Added more info on getting TensorBoard set up in Vertex

If there are other updates you think this needs, lmk and I can work on them. Also, I may add more detail on why you'd want to use training option 1 vs. 2.

### CODE REVIEW

**Comment by amygdala** [comment]
Sorry, somehow I missed this!  I am mid-process of making some other changes, let me finish merging them in first, then look the conflicts that I apparently introduced with your PR.

**Comment by amygdala** [comment]
I believe the issue is that when I was making some other notebook edits, I introduced some big formatting changes by switching from colab to jupyterlab as my notebook editor.  I think it may be too much of a pain to resolve conflicts in the usual way as essentially the whole notebook is the diff 😬.  The changes all look great.  I think it will be easier to create a new PR off HEAD that re-adds them.  Shall I do that, then ping you?  (sorry about this).

**Comment by sararob** [comment]
No prob! Yes, probably easier for me to create a new PR. Just let me know when your changes are ready.

**Comment by amygdala** [comment]
other PR is in, closing this.  Thanks, Sara.

**Pull request closed without merging**
